// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReferralBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferralsCount")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$kkF9EKe7KJxAijZ374He4edBGTSujLGRA48MkMwN9g6PK77IM2H..",
                            ReferralBalance = 0m,
                            ReferralCode = "REF-1-ADMIN",
                            ReferralsCount = 0,
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "claims@gmail.com",
                            FullName = "Claims Officer",
                            IsActive = true,
                            PasswordHash = "$2a$11$kkF9EKe7KJxAijZ374He4edBGTSujLGRA48MkMwN9g6PK77IM2H..",
                            ReferralBalance = 0m,
                            ReferralCode = "REF-2-CLAIMS",
                            ReferralsCount = 0,
                            Role = 4
                        },
                        new
                        {
                            Id = 3,
                            Email = "customer@gmail.com",
                            FullName = "Customer",
                            IsActive = true,
                            PasswordHash = "$2a$11$kkF9EKe7KJxAijZ374He4edBGTSujLGRA48MkMwN9g6PK77IM2H..",
                            ReferralBalance = 0m,
                            ReferralCode = "REF-3-CUSTOMER",
                            ReferralsCount = 0,
                            Role = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PolicyRequestId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyAge")
                        .HasColumnType("int");

                    b.Property<decimal>("PropertyValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyRequestId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimAmount = 5000m,
                            PolicyRequestId = 1,
                            PropertyAddress = "123 Main Street",
                            PropertyAge = 10,
                            PropertyValue = 1000000m,
                            Remarks = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            ClaimAmount = 15000m,
                            PolicyRequestId = 2,
                            PropertyAddress = "456 Commerce Road",
                            PropertyAge = 5,
                            PropertyValue = 5000000m,
                            Remarks = "",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InstallmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyRequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyRequestId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.PolicyRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AgentCommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<decimal>("InstallmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyAge")
                        .HasColumnType("int");

                    b.Property<decimal?>("PropertyValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RiskScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PlanId");

                    b.ToTable("PolicyRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminNotes = "Initial seed policy",
                            AgentCommissionAmount = 0m,
                            CustomerId = 3,
                            Frequency = 0,
                            InstallmentAmount = 0m,
                            InstallmentCount = 0,
                            PlanId = 1,
                            PremiumAmount = 0m,
                            Status = 6,
                            TotalPremium = 0m
                        },
                        new
                        {
                            Id = 2,
                            AdminNotes = "Commercial seed policy",
                            AgentCommissionAmount = 0m,
                            CustomerId = 3,
                            Frequency = 0,
                            InstallmentAmount = 0m,
                            InstallmentCount = 0,
                            PlanId = 2,
                            PremiumAmount = 0m,
                            Status = 6,
                            TotalPremium = 0m
                        });
                });

            modelBuilder.Entity("Domain.Entities.PropertyCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PropertyCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Property Insurance"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PropertyPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AgentCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseCoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasePremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoverageRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("PropertyPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentCommission = 125m,
                            BaseCoverageAmount = 250000m,
                            BasePremium = 1250m,
                            CoverageRate = 0.005m,
                            Frequency = 3,
                            PlanName = "Standard Home Protection",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgentCommission = 600m,
                            BaseCoverageAmount = 1000000m,
                            BasePremium = 8000m,
                            CoverageRate = 0.008m,
                            Frequency = 1,
                            PlanName = "Business Liability Plus",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgentCommission = 4500m,
                            BaseCoverageAmount = 5000000m,
                            BasePremium = 60000m,
                            CoverageRate = 0.012m,
                            Frequency = 2,
                            PlanName = "Industrial Asset Guard",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            AgentCommission = 400m,
                            BaseCoverageAmount = 750000m,
                            BasePremium = 4500m,
                            CoverageRate = 0.006m,
                            Frequency = 3,
                            PlanName = "Luxury Condo Shield",
                            SubCategoryId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.PropertySubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PropertySubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "SUB_RES_01",
                            Name = "Residential Property"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "SUB_COM_02",
                            Name = "Commercial Property"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Code = "SUB_IND_03",
                            Name = "Industrial & Special Use"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Code = "SUB_CON_04",
                            Name = "Property Contents"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Claim", b =>
                {
                    b.HasOne("Domain.Entities.PolicyRequest", "PolicyRequest")
                        .WithMany()
                        .HasForeignKey("PolicyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyRequest");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PolicyRequest", "PolicyRequest")
                        .WithMany()
                        .HasForeignKey("PolicyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PolicyRequest");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.PolicyRequest", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("Domain.Entities.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PropertyPlans", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Domain.Entities.PropertyPlans", b =>
                {
                    b.HasOne("Domain.Entities.PropertySubCategory", "SubCategory")
                        .WithMany("Plans")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Domain.Entities.PropertySubCategory", b =>
                {
                    b.HasOne("Domain.Entities.PropertyCategory", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.PropertyCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Domain.Entities.PropertySubCategory", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
